const express = require('express');
const authRoute = require('./auth.route');
const userRoute = require('./user.route');
const roleRoute = require('./role.route');
const docsRoute = require('./docs.route');
const brandRoute = require('./brand.route');
const categoryRoute = require('./category.route');
const uploadRoute = require('./upload.route');
const addressRoute = require('./address.route');
const movementTypeRoute = require('./movement.type.route');
const colorRoute = require('./color.route');
const strapMaterialRoute = require('./strap.material.route');
const watchRoute = require('./watch.route');
const watchVariantRoute = require('./watch.variant.route');
const cartRoute = require('./cart.route');
const cartItemRoute = require('./cart.item.route');
const orderRoute = require('./order.route');
const orderStatusRoute = require('./order.status.route');

const router = express.Router();

router.use('/auth', authRoute);
router.use('/users', userRoute);
router.use('/roles', roleRoute);
router.use('/docs', docsRoute);
router.use('/brands', brandRoute);
router.use('/categorys', categoryRoute);
router.use('/uploads', uploadRoute);
router.use('/addresses', addressRoute);
router.use('/movement-type', movementTypeRoute);
router.use('/colors', colorRoute);
router.use('/strap-materials', strapMaterialRoute);
router.use('/watches', watchRoute);
router.use('/watch-variants', watchVariantRoute);
router.use('/carts', cartRoute);
router.use('/cart-items', cartItemRoute);
router.use('/orders', orderRoute);
router.use('/order-status', orderStatusRoute);

module.exports = router;
